INSERT INTO [Inventory].[Servers]
(
	[InstanceName]
	, [InstanceNameShort]
	, [ServerName]
	, [ServerNameShort]
	, [Environment]
	, [Tier]
	, [Location]
	, [Description]
	, [LogShippingPrimaryID]
	, [LogShippingSecondaryID]
	, [ExecutionDateTime]
)
	SELECT 'WINSYS1612DEV\INST1' as [InstanceName]
			, 'INST1' as [InstanceNameShort]
			, 'WINSYS1612DEV\INST1' as [ServerName]
			, 'WINSYS1612DEV' as [ServerNameShort]
			, 'Demo' as [Environment]
			, 'Prod' as[Tier]
			, 'Home' as [Location]
			, 'Server for demos.' as [Description]
			, NULL as [LogShippingPrimaryID]
			, NULL as [LogShippingSecondaryID]
			, GETDATE() as [ExecutionDateTime];